version: '3.8'

services:
  mysql:
    image: mysql:8.2
    container_name: sc-fleetfinder-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: sc_fleetfinder
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-time-zone='+00:00'

volumes:
  mysql_data:
