version: '3.8'

services:
  mysql:
    image: mysql:8.2
    container_name: sc-fleetfinder-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: sc_fleetfinder
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-time-zone='+00:00'
    networks:
      - backend-network

  backend:
    image: ${BACKEND_IMAGE_TAG}
    container_name: fleetfinder-backend
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: sc_fleetfinder
      SPRING_PROFILE: prod
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    command: /bin/sh -c "until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done; ./mvnw test || exit 1"
    networks:
      - backend-network

  frontend:
    image: ${FRONTEND_IMAGE_TAG}
    container_name: fleetfinder-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - backend-network

  nginx:
    image: nginx:alpine
    container_name: fleetfinder-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - backend-network                  

volumes:
  mysql_data:

networks:
  backend-network:
    driver: bridge


