version: '3.8'

services:
  mysql:
    image: mysql:8.2
    container_name: sc-fleetfinder-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: sc_fleetfinder
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-time-zone='+00:00'
    networks:
      - backend-network

  backend:
    image: 753149409316.dkr.ecr.us-west-2.amazonaws.com/fleetfinder-backend:v1.0.3
    container_name: fleetfinder-backend
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: sc_fleetfinder
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    command: /bin/sh -c "until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done; ./mvnw test"
    networks:
      - backend-network

  frontend:
    image: 753149409316.dkr.ecr.us-west-2.amazonaws.com/fleetfinder-frontend:v1.0.3
    container_name: fleetfinder-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - backend-network        

volumes:
  mysql_data:

networks:
  backend-network:
    driver: bridge


