CREATE TABLE IF NOT EXISTS listing_template
(
    id_template         BIGINT                                    NOT NULL AUTO_INCREMENT,
    id_user             BIGINT                                    NOT NULL,
    server_id           INT                                       NOT NULL,
    environment_id      INT                                       NOT NULL,
    experience_id       INT                                       NOT NULL,
    listing_title       VARCHAR(65)                               NOT NULL,
    style_id            INT,
    legality_id         INT                                       NOT NULL,
    group_status_id     INT                                       NOT NULL,
    event_schedule      TIMESTAMP,
    category_id         INT                                       NOT NULL,
    subcategory_id      INT,
    pvp_status_id       INT                                       NOT NULL,
    system_id           INT                                       NOT NULL,
    planet_id           INT,
    listing_description VARCHAR(500)                              NOT NULL,
    desired_party_size  TINYINT                                   NOT NULL,
    current_party_size  TINYINT                                   NOT NULL,
    available_roles     VARCHAR(255),
    comms_options       ENUM ('Required', 'Optional', 'No Comms') NOT NULL,
    comms_service       VARCHAR(50),
    creation_timestamp  TIMESTAMP DEFAULT CURRENT_TIMESTAMP       NOT NULL,
    PRIMARY KEY (id_template),
    FOREIGN KEY (id_user) REFERENCES `users` (id_user) ON DELETE CASCADE,
    FOREIGN KEY (server_id) REFERENCES server_region (server_id),
    FOREIGN KEY (environment_id) REFERENCES game_environment (environment_id),
    FOREIGN KEY (experience_id) REFERENCES game_experience (experience_id),
    FOREIGN KEY (style_id) REFERENCES play_style (style_id),
    FOREIGN KEY (legality_id) REFERENCES legality (legality_id),
    FOREIGN KEY (group_status_id) REFERENCES group_status (group_status_id),
    FOREIGN KEY (category_id) REFERENCES gameplay_category (category_id),
    FOREIGN KEY (subcategory_id) REFERENCES gameplay_subcategory (subcategory_id),
    FOREIGN KEY (pvp_status_id) REFERENCES pvp_status (pvp_status_id),
    FOREIGN KEY (system_id) REFERENCES planetary_system (system_id),
    FOREIGN KEY (planet_id) REFERENCES planet_moon_system (planet_id)
)
