spring.application.name=fleets

logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/sc_fleetfinder?serverTimezone=UTC
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Repository detection strategy
spring.data.rest.detection-strategy=ANNOTATED

# DB migration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=sc_fleetfinder
spring.flyway.baseline-on-migrate=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update

# Caching
spring.cache.jcache.config=classpath:ehcache.xml
spring.jpa.properties.hibernate.default_batch_fetch_size=20

spring.data.rest.base-path=/api

allowed.origins=http://localhost:4200

# Keycloak
spring.security.oauth2.resourceserver.jwt.jwk-set-uri = http://localhost:8180/realms/oauthrealm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri = http://localhost:8180/realms/oauthrealm
spring.security.oauth2.client.registration.keycloak-oidc.client-authentication-method=none