spring.application.name=fleets

spring.config.import=optional:file:.env.dev[.properties]
logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/sc_fleetfinder?serverTimezone=UTC
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# DB migration
spring.flyway.enabled=true
spring.flyway.locations=filesystem:src/main/resources/migration
spring.flyway.schemas=sc_fleetfinder
spring.flyway.baseline-on-migrate=false

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.jpa.hibernate.ddl-auto=update

# Caching
spring.cache.jcache.config=classpath:ehcache.xml
spring.jpa.properties.hibernate.default_batch_fetch_size=20

# Keycloak
spring.security.oauth2.resourceserver.jwt.jwk-set-uri = http://localhost:8180/realms/oauthrealm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri = http://localhost:8180/realms/oauthrealm
spring.security.oauth2.client.registration.keycloak-oidc.client-authentication-method=none

#TODO ADD BASE URL FOR PROD


# backend client for keycloak user account control
#TODO configure the discord identity provider for prod, set up the discord application for prod, and create the prod discord bot
#TODO add this in the production properties file and configure the admin client in prod keycloak console
#TODO add the secret from the prod client to prod .env file
keycloak.admin.client-id=dev-backend-service
keycloak.admin.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET}
keycloak.admin.realm=oauthrealm
keycloak.admin.server-url=http://localhost:8180
keycloak.admin.frontend-base-url=http://localhost:4200
keycloak.admin.frontend-client-id=${KEYCLOAK_FRONTEND_CLIENT_ID}

# WebSockets
app.ws.allowed-origins=${WS_ALLOWED_ORIGINS}