spring.application.name=fleets
logging.level.root=INFO

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/sc_fleetfinder?serverTimezone=UTC
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

##DB migration
spring.flyway.enabled=true
spring.flyway.locations=classpath:migration
spring.flyway.baseline-on-migrate=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update

#caching
spring.cache.jcache.config=classpath:ehcache.xml
spring.jpa.properties.hibernate.default_batch_fetch_size=20

# Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri = https://scfleetfinder.com/auth/realms/oauthrealm

# keycloak public url is for generating links to send to the frontend.
# it is the same as admin server url in dev (BUT NOT PROD) because
# the backend does not run in a container in dev and does not have the NGINX proxy routing traffic.
# prod needs different public and server urls because backend and keycloak are both running in containers
# on the same network, communication that stays in the network does not go through nginx so the
# admin.server-url for generating tokens for the backend to authenticate with keycloak needs to be the
# internal port. Whereas links that are generated  and sent to the frontend need the public url because they
# need to route from an external source through NGINX.
# keycloak.admin.frontend-base-url is just the base url used for rerouting after keycloak (back to the app)

keycloak.admin.client-id=${KC_ADMIN_CLIENT_ID}
keycloak.admin.client-secret=${KC_ADMIN_CLIENT_SECRET}
keycloak.admin.realm=oauthrealm
keycloak.admin.server-url=${KC_ADMIN_SERVER_URL}
keycloak.admin.public-url=${KC_ADMIN_PUBLIC_URL}
keycloak.admin.frontend-client-id=${KC_FRONTEND_CLIENT_ID}

# WebSockets
app.frontend-base-url=${FRONTEND_BASE_URL}

# Discord Bot
discord.bot.token=${DISCORD_BOT_TOKEN}

# Push Notifications
vapid.public.key=${VAPID_PUBLIC_PROD_KEY}
vapid.private.key=${VAPID_PRIVATE_PROD_KEY}

# Actuator endpoints
management.endpoints.web.exposure.include=health,prometheus,info,metrics
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=when_authorized
management.metrics.tags.application=fleetfinder
